brew 'bash'
brew 'coreutils'
brew 'fzy'
brew 'git'
brew 'gpg'
brew 'jq'
brew 'neovim'
brew 'stow'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'zplug'
brew 'zsh'

cask_args appdir: "/Applications"
cask 'android-studio'
cask 'dashlane'
cask 'font-fira-code'
cask 'google-chrome'
cask 'iterm2'
cask 'sketch'
cask 'visual-studio-code'
